services:
  pixelmon:
    image: pixelmon-forge:9.1.13
    container_name: pixelmon
    restart: unless-stopped
    environment:
      EULA: "true"
      Xms: 2G
      Xmx: 6G
      SERVER_PORT: 25565
      RCON_ENABLE: "false"
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
